services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: t2
      POSTGRES_PASSWORD: "a0rhJ94XHjiCagF_uLeYtFTbAHT6BB8H"
    volumes:
      - t2_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "BPblP1SOGnRkEtcPTVwQJv6VdtH8SolV"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: t2_test
      POSTGRES_PASSWORD: "I8qseJtFXQssyOQ5zfk0oRneZ-7b_7DS"
    volumes:
      - t2_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "PSPKvaG9633YMHCrn5_YcyKkK8qR2imv"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  t2_data:
  t2_test_data:
